<a href="https://colab.research.google.com/github/hyeranjung/Midterm/blob/main/python_midterm_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 20211020 정혜란 데이터 과학과 분석 _ 4주차 Numpy와 Pandas 기본  

In [2]:
# 8. 패키지와 라이브러리

# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


In [25]:
# 9. Numpy
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [4]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [5]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [7]:
arVal[1][2]

3.14

In [8]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [9]:
arVal[0][2]

't'

In [10]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [11]:
# numpy 패키지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [12]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [13]:
arVal.sum()

AttributeError: ignored

In [14]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [16]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [17]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [18]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [19]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [20]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [21]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [22]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [23]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [26]:
# 10. Pandas

# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [27]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [28]:
pandas_series[0]

30

In [29]:
pandas_series[0][1]

IndexError: ignored

In [30]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [31]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [32]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [33]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [34]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [35]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [36]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [37]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [38]:
# column 삭제
del df['score']

In [39]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [40]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [41]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [42]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [43]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0 -0.394701  0.989625 -0.592976  1.727808 -0.459725
1 -1.852856  0.132579  0.628044  0.504109 -0.043738
2 -1.075302  0.050957 -0.016732 -1.844926  0.061193
3  0.680184  0.698389  1.003873 -1.921468  0.206708
4 -0.877119  0.882268 -1.343423 -0.512111 -1.916922

In [44]:
# 최대값
df.max()

A    0.680184
B    0.989625
C    1.003873
D    1.727808
E    0.206708
dtype: float64

In [45]:
# 최소값
df.min()

A   -1.852856
B    0.050957
C   -1.343423
D   -1.921468
E   -1.916922
dtype: float64

In [46]:
# 평균
df.mean()

A   -0.703959
B    0.550764
C   -0.064243
D   -0.409318
E   -0.430497
dtype: float64

In [47]:
# 표준편차
df.std()

A    0.935326
B    0.432716
C    0.940512
D    1.562033
E    0.867134
dtype: float64

In [48]:
# 누적값
df.cumsum()

A         B         C         D         E
0 -0.394701  0.989625 -0.592976  1.727808 -0.459725
1 -2.247557  1.122204  0.035068  2.231917 -0.503463
2 -3.322859  1.173161  0.018336  0.386991 -0.442270
3 -2.642675  1.871550  1.022210 -1.534478 -0.235562
4 -3.519794  2.753818 -0.321213 -2.046589 -2.152484

In [49]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.703959  0.550764 -0.064243 -0.409318 -0.430497
std    0.935326  0.432716  0.940512  1.562033  0.867134
min   -1.852856  0.050957 -1.343423 -1.921468 -1.916922
25%   -1.075302  0.132579 -0.592976 -1.844926 -0.459725
50%   -0.877119  0.698389 -0.016732 -0.512111 -0.043738
75%   -0.394701  0.882268  0.628044  0.504109  0.061193
max    0.680184  0.989625  1.003873  1.727808  0.206708

In [50]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.394701  0.989625 -0.592976  1.727808 -0.459725        X
1 -1.852856  0.132579  0.628044  0.504109 -0.043738        Y
2 -1.075302  0.050957 -0.016732 -1.844926  0.061193        X
3  0.680184  0.698389  1.003873 -1.921468  0.206708        Y
4 -0.877119  0.882268 -1.343423 -0.512111 -1.916922        Z

In [51]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.735001  0.520291 -0.304854 -0.058559 -0.199266
Y        -0.586336  0.415484  0.815959 -0.708680  0.081485
Z        -0.877119  0.882268 -1.343423 -0.512111 -1.916922